Repository BuildForSDG/team-013-Backend, pull requests merged in 2020-05, with the labels that each got.

#10 remove package-lock.json file
  package-lock.json
Labels: bug

#13 Readme
  .eslintrc.js
  README.md
  package.json
  yarn.lock
Labels: documentation

#14 Fix branch ready to be merged into develop branch
  .idea/codeStyles/Project.xml
  src/app.js
  src/controllers/teacher.controller.js
  src/middleware/auth.js
  src/middleware/uploads.js
  src/model/index.js
  src/model/teacher.model.js
  uploads/image-1589133491323.jpg
  uploads/image-1589227062274.jpg
  uploads/image-1590250289735.jpg
Labels: enhancement

#17 Added question endpoint
  package.json
  src/app.js
  src/controllers/index.js
  src/controllers/question.controller.js
  src/routes/index.js
  src/routes/question.route.js
  target/npmlist.json
  yarn.lock
Labels: enhancement
